#pragma config(Sensor, in3,    lightSensor,    sensorReflection)
#pragma config(Motor,  port1,           leftMotor,     tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port6,           clawMotor,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           armMotor,      tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port10,          rightMotor,    tmotorVex393_HBridge, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	while (true)
	{
		if(SensorValue(lightSensor) < 250)
		{
				motor[clawMotor] = -64;

				wait1Msec(500);
		}
		else
		{
				motor[clawMotor] = 64;

				wait1Msec(200);

	 	}
 	}
}
