#pragma config(Sensor, dgtl1,  rightEncoder,   sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  leftEncoder,    sensorQuadEncoder)
#pragma config(Motor,  port1,           leftMotor,     tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port6,           clawMotor,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           armMotor,      tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port10,          rightMotor,    tmotorVex393_HBridge, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	while (true)
	{
		if(vexRT[Btn6U]==1)
		{
			//vexRT[Btn6U]==0;
			//wait1Msec(2000);
			SensorValue[rightEncoder] = 0;
			SensorValue[leftEncoder] = 0;

			while(SensorValue(leftEncoder) < 1800)
			{
				motor[rightMotor] = 127;
				motor[leftMotor] = 127;
			}
			motor[rightMotor] = 0;
			motor[leftMotor] = 0;

			motor[clawMotor] = -64;
			wait1Msec(700);

			SensorValue[rightEncoder] = 0;
			SensorValue[leftEncoder] = 0;

			while(SensorValue(leftEncoder) < 90)
			{
				motor[rightMotor] = 75;
				motor[leftMotor] = 75;
			}
			motor[rightMotor] = 0;
			motor[leftMotor] = 0;

			motor[clawMotor] = 64;
			wait1Msec(700);

			motor[armMotor] = 64;
			wait1Msec(150);
			motor[armMotor] = 0;

			SensorValue[rightEncoder] = 0;
			SensorValue[leftEncoder] = 0;

			while(SensorValue(leftEncoder) > -2300)
			{
				motor[rightMotor] = -64;
				motor[leftMotor] = -64;
			}
		    motor[rightMotor] = 0;
				motor[leftMotor] = 0;
				break;

			}
	}


}
