#pragma config(Motor,  port1,           leftMotor,     tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port6,           clawMotor,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           armMotor,      tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port10,          rightMotor,    tmotorVex393_HBridge, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	while(1==1) // Infinte while loop
	{
		motor[leftMotor] = vexRT[Ch2]/1.5; // Left Joystick Y value/2
		motor[rightMotor] = vexRT[Ch3]/1.5; // Right Joystick Y value/2
		//Arm controlled by bitton 5
		if(VexRT[Btn6U]==1) //If Button 5U is pressed
		{
			motor[armMotor] = 64; // Raise the Arm
		}
		else if(VexRT[Btn6D] == 1) //Else, if button 5D is pressed
		{
			motor[armMotor] = -64; //Lower the arm
		}
		else               //Else
		{
			motor[armMotor] = 0; //Stop the arm
		}
		// Clawcontrolled by button 6
		if(VexRT[Btn5U]==1) //If Button 6U is pressed
		{
			motor[clawMotor] = 64; // Close the claw
		}
		else if(VexRT[Btn5D] == 1) //Else, if button 5D is pressed
		{
			motor[clawMotor] = -64; //Open the claw
		}
		else               //Else
		{
			motor[clawMotor] = 0; //Stop the claw
		}
	}
}
