#pragma config(Sensor, dgtl1,  rightEncoder,   sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  leftEncoder,    sensorQuadEncoder)
#pragma config(Sensor, dgtl8,  sonarSensor,    sensorSONAR_inch)
#pragma config(Motor,  port1,           leftMotor,     tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port6,           clawMotor,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           armMotor,      tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port10,          rightMotor,    tmotorVex393_HBridge, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
  wait1Msec(2000);

  // Loop while ultrasonic sensor is farhter than 3 inches away
  //from the object || (or) it is '-1'.
  // [ -1 is the value returned when nothing is in its visable range range]

  while(SensorValue(sonarSensor) > 12 || SensorValue(sonarSensor) == -1)
  {
	 motor[rightMotor] = 63;
	 motor[leftMotor] = 63;
 	}
   motor[rightMotor] = 0;
   motor[leftMotor] = 0;

 }
